# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "ox"
gem "aws-sdk-sqs"
gem 'pry'

# https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SQS/Client.html#:~:text=gems/-,aws%2Dsdk%2Dsqs,-/lib/aws%2Dsdk