AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31 # SAM
Resources:
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  InlineLambda:
    Type: AWS::Serverless::Function # especifica que sera criada uma Function
    Properties:
      Handler: function.handler # funcao dentro do codigo que o Lambda inicia a execucao
      Runtime: python3.12 # a tecnologia que roda
      PackageType: Zip # tipo de pacote de implementacao
      CodeUri: ./function/ # pasta com o codigo      